prevent error when working with an empty value
devromans/payment-fee pull request #3
Opened 2016-09-23 06:41 UTC by sandermangel

2016-09-26 07:32 UTC, devromans commented on src/app/code/community/Brander/PaymentFee/Helper/Data.php
> +            foreach ((array)$fees as $fee) {
Probably useless type casting.

2016-09-26 07:35 UTC, devromans commented on src/app/code/community/Brander/PaymentFee/Model/Sales/Quote/Address/Total/Fee.php
> +                    'title' => $amount['bankpayment']['description'],
Why "bankpayment" only?

2016-09-26 07:36 UTC, devromans requested changes

2016-10-19 10:12 UTC, sandermangel commented
@devromans added 2 changes for the comments you added

2016-10-19 12:13 UTC, devromans approved these changes

2016-10-19 12:13 UTC, merged